clear
close all

[FileName,PathName] = uigetfile('*.txt','Select the IMU file');
IMU = importfile(fullfile(PathName,FileName));

IMU=prepare(IMU,100);
IMU=integrate(IMU);

figure
ax1=subplot(3,1,1);
plot(IMU.s,IMU.ax)
title('Ax')
xlabel('s')
ylabel('m/s^2')
ax2=subplot(3,1,2);
plot(IMU.s,IMU.ay)
title('Ay')
xlabel('s')
ylabel('m/s^2')
ax3=subplot(3,1,3);
plot(IMU.s,IMU.az)
title('Az')
xlabel('s')
ylabel('m/s^2')
linkaxes([ax1,ax2,ax3],'x')

figure
plot(IMU.s,IMU.a)
title('mod(A)')
xlabel('s')
ylabel('m/s^2')

figure
ax1=subplot(3,1,1);
plot(IMU.s,IMU.gx)
title('Gx')
xlabel('s')
ylabel('deg/s')
ax2=subplot(3,1,2);
plot(IMU.s,IMU.gy)
title('Gy')
xlabel('s')
ylabel('deg/s')
ax3=subplot(3,1,3);
plot(IMU.s,IMU.gz)
title('Gz')
xlabel('s')
ylabel('deg/s')
linkaxes([ax1,ax2,ax3],'x')

figure
ax1=subplot(3,2,1);
plot(IMU.s,IMU.gx)
title('Gx')
xlabel('s')
ylabel('deg/s')
ax2=subplot(3,2,3);
plot(IMU.s,IMU.gy)
title('Gy')
xlabel('s')
ylabel('deg/s')
ax3=subplot(3,2,5);
plot(IMU.s,IMU.gz)
title('Gz')
xlabel('s')
ylabel('deg/s')
ax4=subplot(3,2,2);
plot(IMU.s,IMU.degx)
xlabel('s')
ylabel('deg')
ax5=subplot(3,2,4);
plot(IMU.s,IMU.degy)
xlabel('s')
ylabel('deg')
ax6=subplot(3,2,6);
plot(IMU.s,IMU.degz)
xlabel('s')
ylabel('deg')
linkaxes([ax1,ax2,ax3],'x')
linkaxes([ax4,ax5,ax6],'x')

figure
ax1=subplot(3,3,1);
plot(IMU.s,IMU.ax)
xlabel('s')
ylabel('m/s^2')
ax2=subplot(3,3,4);
plot(IMU.s,IMU.ay)
xlabel('s')
ylabel('m/s^2')
ax3=subplot(3,3,7);
plot(IMU.s,IMU.az)
xlabel('s')
ylabel('m/s^2')
ax4=subplot(3,3,2);
plot(IMU.s,IMU.vx)
title('x')
xlabel('s')
ylabel('m/s')
ax5=subplot(3,3,5);
plot(IMU.s,IMU.vy)
title('y')
xlabel('s')
ylabel('m/s')
ax6=subplot(3,3,8);
plot(IMU.s,IMU.vz)
title('z')
xlabel('s')
ylabel('m/s')
ax7=subplot(3,3,3);
plot(IMU.s,IMU.x)
xlabel('s')
ylabel('m')
ax8=subplot(3,3,6);
plot(IMU.s,IMU.y)
xlabel('s')
ylabel('m')
ax9=subplot(3,3,9);
plot(IMU.s,IMU.z)
xlabel('s')
ylabel('m')
linkaxes([ax1,ax2,ax3],'x')
linkaxes([ax4,ax5,ax6],'x')
linkaxes([ax7,ax8,ax9],'x')
